"""
    Pydantic models for query operations.
    - QueryRequest: incoming query from user — text only
    - QueryResponse: answer + cited source images returned to user
"""

from pydantic import BaseModel

from app.models.image import ImageResponse

class QueryRequest(BaseModel):
    """User query — text only, namespace resolved from JWT."""
    query: str
    thread_id: str
class QueryResponse(BaseModel):
    """Answer generated by RAG pipeline with cited source images."""
    answer: str
    source_images: list[ImageResponse]
